### ISSUE TITLE
paper issue

### ISSUE THREAD

**Issue by macknight** [idk-wh0am1/Federated-Learning-meets-Homomorphic-Encryption#3]
Hi,
there is a detailed blog here https://research.ibm.com/blog/federated-learning-homomorphic-encryption
Is this project the code base of a paper?

BR

**Comment by banhcuon79** [comment]
yes, btw, my code is based on this [this](https://github.com/ivishalanand/Federated-Learning-on-Hospital-Data/blob/master/second_revision.ipynb) (with cryptography added)

**Comment by macknight** [comment]
> yes, btw, my code is based on this [this](https://github.com/ivishalanand/Federated-Learning-on-Hospital-Data/blob/master/second_revision.ipynb) (with cryptography added)

looks good
